import { Router } from 'express';
// Importaciones
import appRouter from './app';
import cellarRouter from './cellar';
import roleRouter from './role';
import USER_ROUTER from './user';
import loginRouter from './login';
import CUSTOMER_ROUTER from './customer';
import ORDER_ROUTER from './order';
import routeRouter from './route';
import SALE_ROUTER from './sale';
import internalOrderRouter from './internalOrder';
import uploadRouter from './upload';
import readFileRouter from './readFile';
import PRODUCT_ROUTER from './product';
import BRAND_ROUTER from './brand';
import SUBSTANCE_ROUTER from './substance';
import SYMPTOMS_ROUTER from './symptoms';
import PROVIDER_ROUTER from './provider';
import PURCHASE_ROUTER from './purchase';
import TEMP_STORAGE_ROUTER from './tempStorage';
import TEMP_SALE_ROUTER from './tempSale';
import AUTO_STATISTIC_ROUTER from './autoStatistic';
import EXPENSE_ROUTER from './expense';
import ACCOUNTS_PAYABLE_ROUTER from './accountsPayable';
import CHECK_ROUTER from './check';
import CASH_ROUTER from './cash';
import CASH_FLOW_ROUTER from './cashFlow';
import CASH_REQUISITION_ROUTER from './cashRequisition';
import BANK_ROUTER from './bank';
import BANK_ACCOUNT_ROUTER from './bankAccount';
import BANK_FLOW_ROUTER from './bankFlow';
import JOB_DEPARTMENT_ROUTER from './jobDepartment';
import JOB_ROUTER from './job';
import EMPLOYEE_ROUTER from './employee';
import EMPLOYEE_JOB_ROUTER from './employeeJob';
import PAYROLL_ROUTER from './payroll';
import DISCOUNT_ROUTER from './discount';
import RISING_ROUTER from './rising';
import VACATION_ROUTER from './vacation';

const router = Router();

// Rutas
router.use('/vacation', VACATION_ROUTER);
router.use('/rising', RISING_ROUTER);
router.use('/discount', DISCOUNT_ROUTER);
router.use('/payroll', PAYROLL_ROUTER);
router.use('/employeeJob', EMPLOYEE_JOB_ROUTER);
router.use('/employee', EMPLOYEE_ROUTER);
router.use('/job', JOB_ROUTER);
router.use('/jobDepartment', JOB_DEPARTMENT_ROUTER);
router.use('/bankFlow', BANK_FLOW_ROUTER);
router.use('/bankAccount', BANK_ACCOUNT_ROUTER);
router.use('/bank', BANK_ROUTER);
router.use('/cashRequisition', CASH_REQUISITION_ROUTER);
router.use('/cashFlow', CASH_FLOW_ROUTER);
router.use('/cash', CASH_ROUTER);
router.use('/check', CHECK_ROUTER);
router.use('/accountsPayable', ACCOUNTS_PAYABLE_ROUTER);
router.use('/expense', EXPENSE_ROUTER);
router.use('/autoStatistic', AUTO_STATISTIC_ROUTER);
router.use('/tempSale', TEMP_SALE_ROUTER);
router.use('/tempStorage', TEMP_STORAGE_ROUTER);
router.use('/purchase', PURCHASE_ROUTER);
router.use('/provider', PROVIDER_ROUTER);
router.use('/symptoms', SYMPTOMS_ROUTER);
router.use('/substance', SUBSTANCE_ROUTER);
router.use('/brand', BRAND_ROUTER);
router.use('/product', PRODUCT_ROUTER);
router.use('/readFile', readFileRouter);
router.use('/upload', uploadRouter);
router.use('/internalOrder', internalOrderRouter);
router.use('/sale', SALE_ROUTER);
router.use('/route', routeRouter);
router.use('/order', ORDER_ROUTER);
router.use('/customer', CUSTOMER_ROUTER);
router.use('/login', loginRouter);
router.use('/user', USER_ROUTER);
router.use('/role', roleRouter);
router.use('/cellar', cellarRouter);
router.use('/', appRouter);


export default router;
